<?php

session_start();

if (isset($_GET['new']))
{
	session_regenerate_id();
	header('Location: ' . mb_substr($_SERVER['REQUEST_URI'], 0, -(mb_strlen($_SERVER['QUERY_STRING']) + 1)));
	exit;
}

require 'include/functions.php';
require 'include/CssSprite.php';

?><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<title>CSS Sprites Generator</title>
		
		<link type="text/css" rel="stylesheet" href="dpSyntaxHighlighter/styles/shCore.css">
		<link type="text/css" rel="stylesheet" href="dpSyntaxHighlighter/styles/shThemeDefault.css">
		<link type="text/css" rel="stylesheet" href="assets/css-sprites.css">
		<link rel="shortcut icon" href="/favicon.ico">
		
		<style>
		#slider-bg {
			background:transparent url(assets/bg-h.gif) no-repeat scroll 5px 0;
		}
		</style>
		
		<!-- Files generated by http://developer.yahoo.com/yui/articles/hosting/?animation&connection&datasource&datatable&dom&event&json&logger&slider&tabview&uploader&yahoo-dom-event&MIN -->
		<link type="text/css" rel="stylesheet" href="assets/yui-combo.css">
		<script type="text/javascript" src="assets/yui-combo.js"></script>
		
		<script type="text/javascript" src="dpSyntaxHighlighter/src/shCore.js"></script>
		<script type="text/javascript" src="dpSyntaxHighlighter/scripts/shBrushCss.js"></script>
		<script type="text/javascript" src="assets/css-sprites.js"></script>
		<script type="text/javascript">
		var sessionId = <?php print(json_encode(session_id())); ?>;
		SyntaxHighlighter.config.clipboardSwf = 'dpSyntaxHighlighter/scripts/clipboard.swf';
		SyntaxHighlighter.config.strings.expandSource = 'View CSS';
		</script>
	</head>
	<body>
		<div id="page-outer">
			<div id="header">
				<div class="page-inner">
					<h1><a href="http://<?=htmlspecialchars($_SERVER['HTTP_HOST']);?>"><img src="assets/css-sprites.png" alt="CSS Sprite Generator"></a></h1>
					<p>Optimize your website using CSS Sprites! Generate CSS Sprites to speed up your website by reducing HTTP requests.</p>
					<div style="clear: both;"></div>
					<img src="assets/beta-badge.png" alt="" title="It's Web 2.0!" id="beta-badge">
				</div>
			</div>
			
			<div id="tabs" class="yui-navset"> 
				<ul class="yui-nav"> 
					<li class="selected"><a href="#tab1"><em>CSS Sprites</em></a></li> 
					<li><a href="#tab2"><em>About</em></a></li> 
					<li><a href="#tab3"><em>FAQ</em></a></li> 
					<li><a href="#tab4"><em>Latest</em></a></li> 
				</ul>             
				<div class="yui-content"> 
					
					<div class="page-inner sprites" id="tab1">
						<div style="float: left;"> 
							<div id="uploaderContainer"> 
								<div id="uploaderOverlay" style="position: absolute; z-index: 2;"></div> 
								<div id="selectFilesLink" style="z-index: 1;">1. <button id="selectLink" class="button button-1">Upload your Images</button></div>
							</div> 
						</div>
						
						<form action="" onsubmit="s.createSprite(); return false;" id="settings">
							<div style="float: left; padding-left: 30px;">
								2. <button class="button button-2">Create your Sprite</button>
								<a href="#" onclick="return showAdvanced();" id="advanced-handle">advanced</a>
								or add more images
								or <a href="?new">start a new sprite</a>.
							</div>
							<div id="advanced" style="clear: both;">
								<label style="margin: 10px 0;">
									Output Type:
									<select name="output_type" id="output_type" onchange="showJpegSettings(this);">
										<option value="png">PNG - Recommended</option>
										<option value="jpeg">JPEG</option>
										<option value="gif">GIF</option>
									</select>
								</label>
								
								<fieldset id="jpeg-settings" class="yui-skin-sam">
									<legend>JPEG Settings</legend>
									<label>
										JPEG Artefact Removal:
										<input type="checkbox" name="jpeg_reduce_artefacts" id="jpeg_reduce_artefacts">
									</label>
									<label>
										JPEG Quality: <span id="slider-value">0</span>%
										<input type="hidden" name="jpeg_quality" value="75" id="jpeg_quality">
										<div id="slider-bg" class="yui-h-slider" tabindex="-1" title="Slider">
											<div id="slider-thumb" class="yui-slider-thumb"><img src="assets/thumb-n.gif"></div>
										</div>
									</label>
								</fieldset>
								
								<fieldset id="other-settings" class="yui-skin-sam">
									<legend>Other Settings</legend>
									<label>
										CSS Class Prefix:
										<input type="text" name="css_prefix" id="css_prefix">
									</label>
									<label>
										Padding between images:
										<select name="padding" id="padding">
											<option value="0">0px</option>
											<option value="1">1px</option>
											<option value="2">2px</option>
											<option value="3">3px</option>
											<option value="4">4px</option>
											<option value="5">5px</option>
											<option value="10">10px</option>
											<option value="20">20px</option>
										</select>
									</label>
								</fieldset>
							</div>
						</form>
						
						<script type="text/javascript" src="assets/settings.js"></script>
						<script type="text/javascript"> createUploader(); </script>
						
						<div class="yui-skin-sam">
							<div id="dataTableContainer"></div>
						</div>
						
						<div id="loading-container">
							<div id="loading">
								<ul id="messages">
									<li><span>Generating Sprite...</span></li>
									<li><span>Reticulating Splines...</span></li>
									<li><span>Reconfoobling Energymotron...</span>	</li>
									<li><span>Gathering Electrons....</span></li>
									<li><span>Warming Valves...</span></li>
									<li><span>Replacing Hamster...</span></li>
									<li><span>Better loading messages coming in Version 1.1</span></li>
									<li><span>It shouldn't take this long... maybe something broke.</span></li>
								</ul>
							</div>
						</div>
						
						<div id="error-container">
							<div id="error">
								<b>Sorry!</b>
								<div id="error-message"></div>
							</div>
						</div>
						
						<div id="sizes">
							<hr>
							<div>
								Individual Images: <span id="size-before"></span> Estimated Download Time: <strong><span id="download-before"></span> seconds</strong>
							</div>
							<div>
								Sprite: <span id="size-after"></span> Estimated Download Time: <strong><span id="download-after"></span> seconds</strong>
							</div>
						</div>
						
						<a href="#" id="downloadLink" target="_blank">Download Your Sprite Here</a>
						
						<div id="cssContainer"></div>
						<div id="resultsContainer"></div>
					</div>
					
					<div class="page-inner about" id="tab2">
						<h2>CSS Sprites</h2>
						By <a href="http://twitter.com/RoBorg" target="_blank">RoBorg</a>
						<h3>What is a CSS Sprite?</h3>
						<p>
							A CSS Sprite is a load of images lumped together into a single image file.
							They're used as a technique to make your websites load faster, by decreasing the number of HTTP requests your users have to make.
							Each request will contain the overhead of HTTP headers (including cookies) and the connection's latency.
							By using a single image file instead of many, you can dramatically decrease the time it take your pages to load.
						</p>
						
						<h3>What do I get and how do I use it?</h3>
						<p>This tool generates:</p>
						<ul>
							<li>An image file</li>
							<li>A block of CSS code</li>
						</ul>
						<p>
							First upload the image file and add the CSS to your stylesheet.
							Then replace your images with code to load the sprite.
							CSS classes are generated from the image filenames you upload, so for example:
							<code>&lt;img src="icon.png"&gt;</code>
							might become
							<code>&lt;div class="icon"&gt;&lt;/div&gt;</code>
						</p>
					</div>
					
					<div class="page-inner faq" id="tab3">
						<h2>FAQ</h2>
						
						<h3>Who wrote this?</h3>
						<p>
							Greg, AKA <a href="http://www.roborg.co.uk/" target="_blank">RoBorg</a> did (warning, old website!) - I'm a professional PHP programmer for <a href="http://www.justsayplease.co.uk/">Just Say Please</a>.<br>
							You can <a href="http://twitter.com/RoBorg" target="_blank">follow me on Twitter</a>
							</p>
						<div style="margin: auto; width: 210px;">
							<iframe src="http://stackoverflow.com/users/flair/24181.html?theme=clean" marginwidth="0" marginheight="0" frameborder="0"  scrolling="no" width="210px" height="60px"></iframe>
						</div>
						
						<h3>How do I report a bug?</h2>
						<p>At the moment just <a href="http://twitter.com/RoBorg" target="_blank">via Twitter</a></p>
						
						<h3>How long do you store my source images and sprite for?</h3>
						<p>About half an hour to an hour, then they're deleted</p>
						
						<h3>Are images I upload private?</h3>
						<p>I don't give them out or intend to look at them, but can't <em>guarantee</em> they will remain private.</p>
						
						<h3>Is there an API?</h3>
						<p>Yes - see the <a href="api.php?help">CSS Sprites API</a> page.</p>
						
						<h3>Is this project open source</h3>
						<p>Not at the moment, but if I receive enough interest I might clean up the code and release it.</p>
						
						<h3>How is this website written?</h3>
						<p>
							The sprite generator is written in <a href="http://php.net/">PHP</a>, using the <a href="http://php.net/gd">GD image functions</a>.<br>
							The front-end, including the multiple-file uploader is written using <a href="http://developer.yahoo.com/yui/">The Yahoo! User Interface Library (YUI).</a><br>
							<s>Output images are compressed using <a href="http://smush.it">Smush.it</a></s>The Smush.it API has been temporarily removed.
						</p>
					</div>
					
					<div class="page-inner latest" id="tab4">
						<h2>Latest News</h2>
						
						<h3>Nov 2010</h3>
						<ul>
							<li>Fixed off-by-one error in certain circumstances</li>
							<li>Added padding option</li>
							<li>Added CSS class prefix</li>
							<li>Changed layout algorithm for when all images are the same width - now uploading lots of icons will result in a square image instead of a giant column</li>
							<li>Upgraded to PHP 5.3 - now grayscale PNGs are loaded correctly!</li>
							<li>Added PNG compression and filters</li>
						</ul>
					</div>
				</div>
			</div>
			<script type="text/javascript">
			var tabView = new YAHOO.widget.TabView('tabs');
			</script>
			
			<div id="footer">
				<div class="page-inner">
				</div>
			</div>
		</div>
		
		<script type="text/javascript">
		var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
		document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
		</script>
		<script type="text/javascript">
		try {
		var pageTracker = _gat._getTracker("UA-280848-6");
		pageTracker._trackPageview();
		} catch(err) {}</script>
	</body>
</html>